### ISSUE TITLE
Can checkformat AUTO correct some problems

### ISSUE THREAD

**Issue by yguitton** [workflow4metabolomics/checkformat#1]
Hi, sometimes checkformat propose good solution to correct the matrices, may be we can find a way to automatically apply correction an d re-run checkformat on those autocorrected matrices.

exemple: missing X in front of file names X2015.ZZZ (just launch make.names on sampleMetaData(row.names)  and dataMatrix (colnames) if they are different

or try to rename variableMetadat (row.names) and dataMatrix (row.names) and check if they are finally equal

**Comment by yguitton** [comment]
could it be the same for Quality metrics and in the statistics tools that use the check format as first step?

**Comment by ethevenot** [comment]
Hi Yann,
The Check Format (3.0.0) has been modified to re-order samples or variables according to the metadata files and (optionnaly) to make the names syntactically valid.
An internal re-ordering of the samples has also been added to Quality Metrics to help the users at the end of the preprocessing and for compatibility with Melanie's script.
I do not plan to include modifications into the other tools because I think it is important that users are aware that the formats of their tables are correct or not, and because Check Format now helps them to automatically correct the format.
Best,
Etienne.

**Comment by yguitton** [comment]
Great thanks
Yann

Le 22 janv. 2018 17:17, "Etienne Thévenot" <notifications@github.com> a
écrit :
